version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: bank_postgres
    environment:
      POSTGRES_DB: bank_cards
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: orion
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  app:
    build: .
    container_name: bank_app
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/bank_cards
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: orion
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
      SPRING_LIQUIBASE_CHANGE_LOG: classpath:db/migration/changelog-master.yaml
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/app/logs
