#
# application.yml — главный конфигурационный файл Spring Boot.

#Что нужно сделать:
#  - Указать настройки подключения к базе данных.
#  - Указать порт приложения.
#  - Настроить параметры безопасности и JWT.
#  - Включить Swagger UI.

server:
  port: 8080   # Порт приложения

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bank_cards?currentSchema=public
    username: postgres
    password: orion
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none   # Управление схемой через Liquibase
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  liquibase:
    change-log: classpath:db/migration/changelog-master.yml

# Настройки безопасности и JWT
security:
  jwt:
    secret: "superSecretKeyForJWTGeneration123456789"   # Секретный ключ
    expiration: 3600000   # Время жизни токена (мс) = 1 час
    issuer: "bankcards-app"

# Swagger / OpenAPI
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    try-it-out-enabled: true
    filter: true
    operationsSorter: method
    tagsSorter: alpha
